using System.Runtime.InteropServices;
using System.Text;
using Veldrid.OpenXR.Native;

namespace Veldrid.OpenXR;
public readonly struct XRExtensionDescriptor
{
    public readonly string ExtensionName;
    public readonly uint ExtensionVersion;
    public XRExtensionDescriptor(string extensionName, uint extensionVersion)
    {
        ExtensionName = extensionName;
        ExtensionVersion = extensionVersion;
    }
    public unsafe XRExtensionDescriptor(XrExtensionProperties extension)
    {
        ExtensionName = Marshal.PtrToStringUTF8((IntPtr)extension.extensionName);
        ExtensionVersion = extension.extensionVersion;
    }
    public static unsafe explicit operator XrExtensionProperties(XRExtensionDescriptor extension)
    {
        XrExtensionProperties extProps = new()
        {
            type = XrStructureType.XR_TYPE_EXTENSION_PROPERTIES,
            extensionVersion = extension.ExtensionVersion,
            next = null
        };
        extProps.extensionName[Encoding.UTF8.GetBytes(extension.ExtensionName.AsSpan(), new Span<byte>(extProps.extensionName, (int)OpenXRNative.XR_MAX_EXTENSION_NAME_SIZE)) + 1] = 0;
        return extProps;
    }
    public static explicit operator XRExtensionDescriptor(XrExtensionProperties extension) => new(extension);
    public static implicit operator string(XRExtensionDescriptor extension) => extension.ExtensionName;
    #region Extensions
    public static XRExtensionDescriptor XR_KHR_ANDROID_THREAD_SETTINGS => new(OpenXRNativeExtensionConstants.XR_KHR_ANDROID_THREAD_SETTINGS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_android_thread_settings_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_ANDROID_SURFACE_SWAPCHAIN => new(OpenXRNativeExtensionConstants.XR_KHR_ANDROID_SURFACE_SWAPCHAIN_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_android_surface_swapchain_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_COMPOSITION_LAYER_CUBE => new(OpenXRNativeExtensionConstants.XR_KHR_COMPOSITION_LAYER_CUBE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_composition_layer_cube_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_ANDROID_CREATE_INSTANCE => new(OpenXRNativeExtensionConstants.XR_KHR_ANDROID_CREATE_INSTANCE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_android_create_instance_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_COMPOSITION_LAYER_DEPTH => new(OpenXRNativeExtensionConstants.XR_KHR_COMPOSITION_LAYER_DEPTH_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_composition_layer_depth_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_VULKAN_SWAPCHAIN_FORMAT_LIST => new(OpenXRNativeExtensionConstants.XR_KHR_VULKAN_SWAPCHAIN_FORMAT_LIST_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_vulkan_swapchain_format_list_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_PERFORMANCE_SETTINGS => new(OpenXRNativeExtensionConstants.XR_EXT_PERFORMANCE_SETTINGS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_performance_settings_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_THERMAL_QUERY => new(OpenXRNativeExtensionConstants.XR_EXT_THERMAL_QUERY_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_thermal_query_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_COMPOSITION_LAYER_CYLINDER => new(OpenXRNativeExtensionConstants.XR_KHR_COMPOSITION_LAYER_CYLINDER_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_composition_layer_cylinder_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_COMPOSITION_LAYER_EQUIRECT => new(OpenXRNativeExtensionConstants.XR_KHR_COMPOSITION_LAYER_EQUIRECT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_composition_layer_equirect_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_DEBUG_UTILS => new(OpenXRNativeExtensionConstants.XR_EXT_DEBUG_UTILS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_debug_utils_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_OPENGL_ENABLE => new(OpenXRNativeExtensionConstants.XR_KHR_OPENGL_ENABLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_opengl_enable_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_OPENGL_ES_ENABLE => new(OpenXRNativeExtensionConstants.XR_KHR_OPENGL_ES_ENABLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_opengl_es_enable_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_VULKAN_ENABLE => new(OpenXRNativeExtensionConstants.XR_KHR_VULKAN_ENABLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_vulkan_enable_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_D3D11_ENABLE => new(OpenXRNativeExtensionConstants.XR_KHR_D3D11_ENABLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_D3D11_enable_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_D3D12_ENABLE => new(OpenXRNativeExtensionConstants.XR_KHR_D3D12_ENABLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_D3D12_enable_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_EYE_GAZE_INTERACTION => new(OpenXRNativeExtensionConstants.XR_EXT_EYE_GAZE_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_eye_gaze_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_VISIBILITY_MASK => new(OpenXRNativeExtensionConstants.XR_KHR_VISIBILITY_MASK_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_visibility_mask_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXTX_OVERLAY => new(OpenXRNativeExtensionConstants.XR_EXTX_OVERLAY_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXTX_overlay_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_COMPOSITION_LAYER_COLOR_SCALE_BIAS => new(OpenXRNativeExtensionConstants.XR_KHR_COMPOSITION_LAYER_COLOR_SCALE_BIAS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_composition_layer_color_scale_bias_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_WIN32_CONVERT_PERFORMANCE_COUNTER_TIME => new(OpenXRNativeExtensionConstants.XR_KHR_WIN32_CONVERT_PERFORMANCE_COUNTER_TIME_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_win32_convert_performance_counter_time_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_CONVERT_TIMESPEC_TIME => new(OpenXRNativeExtensionConstants.XR_KHR_CONVERT_TIMESPEC_TIME_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_convert_timespec_time_SPEC_VERSION);
    public static XRExtensionDescriptor XR_VARJO_QUAD_VIEWS => new(OpenXRNativeExtensionConstants.XR_VARJO_QUAD_VIEWS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_VARJO_quad_views_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_UNBOUNDED_REFERENCE_SPACE => new(OpenXRNativeExtensionConstants.XR_MSFT_UNBOUNDED_REFERENCE_SPACE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_unbounded_reference_space_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_SPATIAL_ANCHOR => new(OpenXRNativeExtensionConstants.XR_MSFT_SPATIAL_ANCHOR_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_spatial_anchor_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_COMPOSITION_LAYER_IMAGE_LAYOUT => new(OpenXRNativeExtensionConstants.XR_FB_COMPOSITION_LAYER_IMAGE_LAYOUT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_composition_layer_image_layout_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_COMPOSITION_LAYER_ALPHA_BLEND => new(OpenXRNativeExtensionConstants.XR_FB_COMPOSITION_LAYER_ALPHA_BLEND_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_composition_layer_alpha_blend_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MND_HEADLESS => new(OpenXRNativeExtensionConstants.XR_MND_HEADLESS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MND_headless_SPEC_VERSION);
    public static XRExtensionDescriptor XR_OCULUS_ANDROID_SESSION_STATE_ENABLE => new(OpenXRNativeExtensionConstants.XR_OCULUS_ANDROID_SESSION_STATE_ENABLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_OCULUS_android_session_state_enable_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_VIEW_CONFIGURATION_DEPTH_RANGE => new(OpenXRNativeExtensionConstants.XR_EXT_VIEW_CONFIGURATION_DEPTH_RANGE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_view_configuration_depth_range_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_CONFORMANCE_AUTOMATION => new(OpenXRNativeExtensionConstants.XR_EXT_CONFORMANCE_AUTOMATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_conformance_automation_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MNDX_EGL_ENABLE => new(OpenXRNativeExtensionConstants.XR_MNDX_EGL_ENABLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MNDX_egl_enable_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_SPATIAL_GRAPH_BRIDGE => new(OpenXRNativeExtensionConstants.XR_MSFT_SPATIAL_GRAPH_BRIDGE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_spatial_graph_bridge_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_HAND_INTERACTION => new(OpenXRNativeExtensionConstants.XR_MSFT_HAND_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_hand_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_HAND_TRACKING => new(OpenXRNativeExtensionConstants.XR_EXT_HAND_TRACKING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_hand_tracking_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_HAND_TRACKING_MESH => new(OpenXRNativeExtensionConstants.XR_MSFT_HAND_TRACKING_MESH_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_hand_tracking_mesh_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_SECONDARY_VIEW_CONFIGURATION => new(OpenXRNativeExtensionConstants.XR_MSFT_SECONDARY_VIEW_CONFIGURATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_secondary_view_configuration_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_FIRST_PERSON_OBSERVER => new(OpenXRNativeExtensionConstants.XR_MSFT_FIRST_PERSON_OBSERVER_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_first_person_observer_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_CONTROLLER_MODEL => new(OpenXRNativeExtensionConstants.XR_MSFT_CONTROLLER_MODEL_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_controller_model_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_PERCEPTION_ANCHOR_INTEROP => new(OpenXRNativeExtensionConstants.XR_MSFT_PERCEPTION_ANCHOR_INTEROP_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_perception_anchor_interop_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_WIN32_APPCONTAINER_COMPATIBLE => new(OpenXRNativeExtensionConstants.XR_EXT_WIN32_APPCONTAINER_COMPATIBLE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_win32_appcontainer_compatible_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EPIC_VIEW_CONFIGURATION_FOV => new(OpenXRNativeExtensionConstants.XR_EPIC_VIEW_CONFIGURATION_FOV_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EPIC_view_configuration_fov_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_HOLOGRAPHIC_WINDOW_ATTACHMENT => new(OpenXRNativeExtensionConstants.XR_MSFT_HOLOGRAPHIC_WINDOW_ATTACHMENT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_holographic_window_attachment_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_COMPOSITION_LAYER_REPROJECTION => new(OpenXRNativeExtensionConstants.XR_MSFT_COMPOSITION_LAYER_REPROJECTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_composition_layer_reprojection_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HUAWEI_CONTROLLER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_HUAWEI_CONTROLLER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HUAWEI_controller_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_ANDROID_SURFACE_SWAPCHAIN_CREATE => new(OpenXRNativeExtensionConstants.XR_FB_ANDROID_SURFACE_SWAPCHAIN_CREATE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_android_surface_swapchain_create_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SWAPCHAIN_UPDATE_STATE => new(OpenXRNativeExtensionConstants.XR_FB_SWAPCHAIN_UPDATE_STATE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_swapchain_update_state_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_COMPOSITION_LAYER_SECURE_CONTENT => new(OpenXRNativeExtensionConstants.XR_FB_COMPOSITION_LAYER_SECURE_CONTENT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_composition_layer_secure_content_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_BODY_TRACKING => new(OpenXRNativeExtensionConstants.XR_FB_BODY_TRACKING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_body_tracking_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_DPAD_BINDING => new(OpenXRNativeExtensionConstants.XR_EXT_DPAD_BINDING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_dpad_binding_SPEC_VERSION);
    public static XRExtensionDescriptor XR_VALVE_ANALOG_THRESHOLD => new(OpenXRNativeExtensionConstants.XR_VALVE_ANALOG_THRESHOLD_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_VALVE_analog_threshold_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_HAND_JOINTS_MOTION_RANGE => new(OpenXRNativeExtensionConstants.XR_EXT_HAND_JOINTS_MOTION_RANGE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_hand_joints_motion_range_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_LOADER_INIT => new(OpenXRNativeExtensionConstants.XR_KHR_LOADER_INIT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_loader_init_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_LOADER_INIT_ANDROID => new(OpenXRNativeExtensionConstants.XR_KHR_LOADER_INIT_ANDROID_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_loader_init_android_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_VULKAN_ENABLE2 => new(OpenXRNativeExtensionConstants.XR_KHR_VULKAN_ENABLE2_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_vulkan_enable2_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_COMPOSITION_LAYER_EQUIRECT2 => new(OpenXRNativeExtensionConstants.XR_KHR_COMPOSITION_LAYER_EQUIRECT2_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_composition_layer_equirect2_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_SAMSUNG_ODYSSEY_CONTROLLER => new(OpenXRNativeExtensionConstants.XR_EXT_SAMSUNG_ODYSSEY_CONTROLLER_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_samsung_odyssey_controller_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_HP_MIXED_REALITY_CONTROLLER => new(OpenXRNativeExtensionConstants.XR_EXT_HP_MIXED_REALITY_CONTROLLER_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_hp_mixed_reality_controller_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MND_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT => new(OpenXRNativeExtensionConstants.XR_MND_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MND_swapchain_usage_input_attachment_bit_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_SCENE_UNDERSTANDING => new(OpenXRNativeExtensionConstants.XR_MSFT_SCENE_UNDERSTANDING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_scene_understanding_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_SCENE_UNDERSTANDING_SERIALIZATION => new(OpenXRNativeExtensionConstants.XR_MSFT_SCENE_UNDERSTANDING_SERIALIZATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_scene_understanding_serialization_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_DISPLAY_REFRESH_RATE => new(OpenXRNativeExtensionConstants.XR_FB_DISPLAY_REFRESH_RATE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_display_refresh_rate_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTC_VIVE_COSMOS_CONTROLLER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_HTC_VIVE_COSMOS_CONTROLLER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTC_vive_cosmos_controller_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTCX_VIVE_TRACKER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_HTCX_VIVE_TRACKER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTCX_vive_tracker_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTC_FACIAL_TRACKING => new(OpenXRNativeExtensionConstants.XR_HTC_FACIAL_TRACKING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTC_facial_tracking_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTC_VIVE_FOCUS3_CONTROLLER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_HTC_VIVE_FOCUS3_CONTROLLER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTC_vive_focus3_controller_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTC_HAND_INTERACTION => new(OpenXRNativeExtensionConstants.XR_HTC_HAND_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTC_hand_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTC_VIVE_WRIST_TRACKER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_HTC_VIVE_WRIST_TRACKER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTC_vive_wrist_tracker_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_COLOR_SPACE => new(OpenXRNativeExtensionConstants.XR_FB_COLOR_SPACE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_color_space_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_HAND_TRACKING_MESH => new(OpenXRNativeExtensionConstants.XR_FB_HAND_TRACKING_MESH_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_hand_tracking_mesh_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_HAND_TRACKING_AIM => new(OpenXRNativeExtensionConstants.XR_FB_HAND_TRACKING_AIM_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_hand_tracking_aim_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_HAND_TRACKING_CAPSULES => new(OpenXRNativeExtensionConstants.XR_FB_HAND_TRACKING_CAPSULES_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_hand_tracking_capsules_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPATIAL_ENTITY => new(OpenXRNativeExtensionConstants.XR_FB_SPATIAL_ENTITY_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_spatial_entity_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_FOVEATION => new(OpenXRNativeExtensionConstants.XR_FB_FOVEATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_foveation_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_FOVEATION_CONFIGURATION => new(OpenXRNativeExtensionConstants.XR_FB_FOVEATION_CONFIGURATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_foveation_configuration_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_KEYBOARD_TRACKING => new(OpenXRNativeExtensionConstants.XR_FB_KEYBOARD_TRACKING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_keyboard_tracking_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_TRIANGLE_MESH => new(OpenXRNativeExtensionConstants.XR_FB_TRIANGLE_MESH_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_triangle_mesh_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_PASSTHROUGH => new(OpenXRNativeExtensionConstants.XR_FB_PASSTHROUGH_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_passthrough_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_RENDER_MODEL => new(OpenXRNativeExtensionConstants.XR_FB_RENDER_MODEL_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_render_model_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_BINDING_MODIFICATION => new(OpenXRNativeExtensionConstants.XR_KHR_BINDING_MODIFICATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_binding_modification_SPEC_VERSION);
    public static XRExtensionDescriptor XR_VARJO_FOVEATED_RENDERING => new(OpenXRNativeExtensionConstants.XR_VARJO_FOVEATED_RENDERING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_VARJO_foveated_rendering_SPEC_VERSION);
    public static XRExtensionDescriptor XR_VARJO_COMPOSITION_LAYER_DEPTH_TEST => new(OpenXRNativeExtensionConstants.XR_VARJO_COMPOSITION_LAYER_DEPTH_TEST_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_VARJO_composition_layer_depth_test_SPEC_VERSION);
    public static XRExtensionDescriptor XR_VARJO_ENVIRONMENT_DEPTH_ESTIMATION => new(OpenXRNativeExtensionConstants.XR_VARJO_ENVIRONMENT_DEPTH_ESTIMATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_VARJO_environment_depth_estimation_SPEC_VERSION);
    public static XRExtensionDescriptor XR_VARJO_MARKER_TRACKING => new(OpenXRNativeExtensionConstants.XR_VARJO_MARKER_TRACKING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_VARJO_marker_tracking_SPEC_VERSION);
    public static XRExtensionDescriptor XR_VARJO_VIEW_OFFSET => new(OpenXRNativeExtensionConstants.XR_VARJO_VIEW_OFFSET_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_VARJO_view_offset_SPEC_VERSION);
    public static XRExtensionDescriptor XR_ML_ML2_CONTROLLER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_ML_ML2_CONTROLLER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_ML_ml2_controller_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_ML_FRAME_END_INFO => new(OpenXRNativeExtensionConstants.XR_ML_FRAME_END_INFO_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_ML_frame_end_info_SPEC_VERSION);
    public static XRExtensionDescriptor XR_ML_GLOBAL_DIMMER => new(OpenXRNativeExtensionConstants.XR_ML_GLOBAL_DIMMER_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_ML_global_dimmer_SPEC_VERSION);
    public static XRExtensionDescriptor XR_ML_COMPAT => new(OpenXRNativeExtensionConstants.XR_ML_COMPAT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_ML_compat_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MSFT_SPATIAL_ANCHOR_PERSISTENCE => new(OpenXRNativeExtensionConstants.XR_MSFT_SPATIAL_ANCHOR_PERSISTENCE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MSFT_spatial_anchor_persistence_SPEC_VERSION);
    public static XRExtensionDescriptor XR_ULTRALEAP_HAND_TRACKING_FOREARM => new(OpenXRNativeExtensionConstants.XR_ULTRALEAP_HAND_TRACKING_FOREARM_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_ULTRALEAP_hand_tracking_forearm_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPATIAL_ENTITY_QUERY => new(OpenXRNativeExtensionConstants.XR_FB_SPATIAL_ENTITY_QUERY_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_spatial_entity_query_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPATIAL_ENTITY_STORAGE => new(OpenXRNativeExtensionConstants.XR_FB_SPATIAL_ENTITY_STORAGE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_spatial_entity_storage_SPEC_VERSION);
    public static XRExtensionDescriptor XR_OCULUS_AUDIO_DEVICE_GUID => new(OpenXRNativeExtensionConstants.XR_OCULUS_AUDIO_DEVICE_GUID_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_OCULUS_audio_device_guid_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_FOVEATION_VULKAN => new(OpenXRNativeExtensionConstants.XR_FB_FOVEATION_VULKAN_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_foveation_vulkan_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SWAPCHAIN_UPDATE_STATE_ANDROID_SURFACE => new(OpenXRNativeExtensionConstants.XR_FB_SWAPCHAIN_UPDATE_STATE_ANDROID_SURFACE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_swapchain_update_state_android_surface_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SWAPCHAIN_UPDATE_STATE_OPENGL_ES => new(OpenXRNativeExtensionConstants.XR_FB_SWAPCHAIN_UPDATE_STATE_OPENGL_ES_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_swapchain_update_state_opengl_es_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SWAPCHAIN_UPDATE_STATE_VULKAN => new(OpenXRNativeExtensionConstants.XR_FB_SWAPCHAIN_UPDATE_STATE_VULKAN_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_swapchain_update_state_vulkan_SPEC_VERSION);
    public static XRExtensionDescriptor XR_KHR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT => new(OpenXRNativeExtensionConstants.XR_KHR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_KHR_swapchain_usage_input_attachment_bit_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_TOUCH_CONTROLLER_PRO => new(OpenXRNativeExtensionConstants.XR_FB_TOUCH_CONTROLLER_PRO_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_touch_controller_pro_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPATIAL_ENTITY_SHARING => new(OpenXRNativeExtensionConstants.XR_FB_SPATIAL_ENTITY_SHARING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_spatial_entity_sharing_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPACE_WARP => new(OpenXRNativeExtensionConstants.XR_FB_SPACE_WARP_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_space_warp_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_HAPTIC_AMPLITUDE_ENVELOPE => new(OpenXRNativeExtensionConstants.XR_FB_HAPTIC_AMPLITUDE_ENVELOPE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_haptic_amplitude_envelope_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SCENE => new(OpenXRNativeExtensionConstants.XR_FB_SCENE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_scene_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_PALM_POSE => new(OpenXRNativeExtensionConstants.XR_EXT_PALM_POSE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_palm_pose_SPEC_VERSION);
    public static XRExtensionDescriptor XR_ALMALENCE_DIGITAL_LENS_CONTROL => new(OpenXRNativeExtensionConstants.XR_ALMALENCE_DIGITAL_LENS_CONTROL_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_ALMALENCE_digital_lens_control_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SCENE_CAPTURE => new(OpenXRNativeExtensionConstants.XR_FB_SCENE_CAPTURE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_scene_capture_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPATIAL_ENTITY_CONTAINER => new(OpenXRNativeExtensionConstants.XR_FB_SPATIAL_ENTITY_CONTAINER_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_spatial_entity_container_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_FOVEATION_EYE_TRACKED => new(OpenXRNativeExtensionConstants.XR_META_FOVEATION_EYE_TRACKED_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_foveation_eye_tracked_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_FACE_TRACKING => new(OpenXRNativeExtensionConstants.XR_FB_FACE_TRACKING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_face_tracking_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_EYE_TRACKING_SOCIAL => new(OpenXRNativeExtensionConstants.XR_FB_EYE_TRACKING_SOCIAL_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_eye_tracking_social_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_PASSTHROUGH_KEYBOARD_HANDS => new(OpenXRNativeExtensionConstants.XR_FB_PASSTHROUGH_KEYBOARD_HANDS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_passthrough_keyboard_hands_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_COMPOSITION_LAYER_SETTINGS => new(OpenXRNativeExtensionConstants.XR_FB_COMPOSITION_LAYER_SETTINGS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_composition_layer_settings_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_TOUCH_CONTROLLER_PROXIMITY => new(OpenXRNativeExtensionConstants.XR_FB_TOUCH_CONTROLLER_PROXIMITY_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_touch_controller_proximity_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_HAPTIC_PCM => new(OpenXRNativeExtensionConstants.XR_FB_HAPTIC_PCM_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_haptic_pcm_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_COMPOSITION_LAYER_DEPTH_TEST => new(OpenXRNativeExtensionConstants.XR_FB_COMPOSITION_LAYER_DEPTH_TEST_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_composition_layer_depth_test_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_LOCAL_DIMMING => new(OpenXRNativeExtensionConstants.XR_META_LOCAL_DIMMING_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_local_dimming_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_PASSTHROUGH_PREFERENCES => new(OpenXRNativeExtensionConstants.XR_META_PASSTHROUGH_PREFERENCES_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_passthrough_preferences_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_VIRTUAL_KEYBOARD => new(OpenXRNativeExtensionConstants.XR_META_VIRTUAL_KEYBOARD_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_virtual_keyboard_SPEC_VERSION);
    public static XRExtensionDescriptor XR_OCULUS_EXTERNAL_CAMERA => new(OpenXRNativeExtensionConstants.XR_OCULUS_EXTERNAL_CAMERA_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_OCULUS_external_camera_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_VULKAN_SWAPCHAIN_CREATE_INFO => new(OpenXRNativeExtensionConstants.XR_META_VULKAN_SWAPCHAIN_CREATE_INFO_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_vulkan_swapchain_create_info_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_PERFORMANCE_METRICS => new(OpenXRNativeExtensionConstants.XR_META_PERFORMANCE_METRICS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_performance_metrics_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPATIAL_ENTITY_STORAGE_BATCH => new(OpenXRNativeExtensionConstants.XR_FB_SPATIAL_ENTITY_STORAGE_BATCH_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_spatial_entity_storage_batch_SPEC_VERSION);
    public static XRExtensionDescriptor XR_FB_SPATIAL_ENTITY_USER => new(OpenXRNativeExtensionConstants.XR_FB_SPATIAL_ENTITY_USER_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_FB_spatial_entity_user_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_HEADSET_ID => new(OpenXRNativeExtensionConstants.XR_META_HEADSET_ID_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_headset_id_SPEC_VERSION);
    public static XRExtensionDescriptor XR_META_PASSTHROUGH_COLOR_LUT => new(OpenXRNativeExtensionConstants.XR_META_PASSTHROUGH_COLOR_LUT_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_META_passthrough_color_lut_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_UUID => new(OpenXRNativeExtensionConstants.XR_EXT_UUID_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_uuid_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_HAND_INTERACTION => new(OpenXRNativeExtensionConstants.XR_EXT_HAND_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_hand_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_QCOM_TRACKING_OPTIMIZATION_SETTINGS => new(OpenXRNativeExtensionConstants.XR_QCOM_TRACKING_OPTIMIZATION_SETTINGS_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_QCOM_tracking_optimization_settings_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTC_PASSTHROUGH => new(OpenXRNativeExtensionConstants.XR_HTC_PASSTHROUGH_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTC_passthrough_SPEC_VERSION);
    public static XRExtensionDescriptor XR_HTC_FOVEATION => new(OpenXRNativeExtensionConstants.XR_HTC_FOVEATION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_HTC_foveation_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_ACTIVE_ACTION_SET_PRIORITY => new(OpenXRNativeExtensionConstants.XR_EXT_ACTIVE_ACTION_SET_PRIORITY_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_active_action_set_priority_SPEC_VERSION);
    public static XRExtensionDescriptor XR_MNDX_FORCE_FEEDBACK_CURL => new(OpenXRNativeExtensionConstants.XR_MNDX_FORCE_FEEDBACK_CURL_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_MNDX_force_feedback_curl_SPEC_VERSION);
    public static XRExtensionDescriptor XR_BD_CONTROLLER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_BD_CONTROLLER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_BD_controller_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_LOCAL_FLOOR => new(OpenXRNativeExtensionConstants.XR_EXT_LOCAL_FLOOR_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_local_floor_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_HAND_TRACKING_DATA_SOURCE => new(OpenXRNativeExtensionConstants.XR_EXT_HAND_TRACKING_DATA_SOURCE_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_hand_tracking_data_source_SPEC_VERSION);
    public static XRExtensionDescriptor XR_EXT_PLANE_DETECTION => new(OpenXRNativeExtensionConstants.XR_EXT_PLANE_DETECTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_EXT_plane_detection_SPEC_VERSION);
    public static XRExtensionDescriptor XR_OPPO_CONTROLLER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_OPPO_CONTROLLER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_OPPO_controller_interaction_SPEC_VERSION);
    public static XRExtensionDescriptor XR_YVR_CONTROLLER_INTERACTION => new(OpenXRNativeExtensionConstants.XR_YVR_CONTROLLER_INTERACTION_EXTENSION_NAME, OpenXRNativeExtensionConstants.XR_YVR_controller_interaction_SPEC_VERSION);
    #endregion
}